(function (lib, img, cjs) {

var p; // shortcut to reference prototypes
var rect; // used to reference frame bounds

// stage content:
(lib.tolanztemp = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(384,512,0,0);
p.frameBounds = [rect];


// symbols:
(lib.btnGame = function() {
	this.initialize(img.btnGame);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,107,52);


(lib.btnHome = function() {
	this.initialize(img.btnHome);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,62,57);


(lib.btnNext = function() {
	this.initialize(img.btnNext);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,62,57);


(lib.btnPrev = function() {
	this.initialize(img.btnPrev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,62,57);


(lib.page1 = function() {
	this.initialize(img.page1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,768);


(lib.page2 = function() {
	this.initialize(img.page2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,768);


(lib.page3 = function() {
	this.initialize(img.page3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,768);


(lib.page4 = function() {
	this.initialize(img.page4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,768);


(lib.btnPrev_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.btnPrev();
	this.instance.setTransform(-30.9,-28.4);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-30.9,-28.4,62,57);
p.frameBounds = [rect];


(lib.btnPlay = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#84C04F").s().p("AD/DHQgOgJgHgTIgQgsIh6AAIgRAsQgIATgOAJQgNAIgQAAQgMAAgKgEQgJgEgJgHQgJgHgFgKQgFgKAAgLQAAgNAFgLICGkpQAIgUAQgJQAPgKAQAAQAQAAAPAKQAOAJAIAUIB9EpQAFALAAANQAAALgFAKQgGAKgJAHQgJAHgLAEQgLAEgLAAQgQAAgNgIgACEAlIA3AAIgahIgAGqDAQgRgPAAgbIAAh6IhciSQgKgPAAgOQAAgMAFgKQAGgKAIgIQAJgHALgGQALgEALAAQAOAAAMAHQAMAIAJAOIAyBXIAzhXQAJgOAMgIQAMgHAOAAQALAAALAEQALAGAJAHQAIAIAFAKQAFAKAAAMQAAAOgJAPIhbCSIAAB6QAAAbgRAPQgRAPgXAAQgYAAgQgPgAjcDPQg5AAAAg6IAAkoQAAgbARgPQARgOAXAAQAXAAARAOQARAPAAAbIAADvIA8AAQAaAAAOARQAOAQAAAYQAAAYgOARQgOARgaAAgApgDAQgOgPAAgcIAAkoQAAg5A3AAIB0AAQAlAAAbALQAbALASATQASATAIAXQAJAZAAAYQAAAZgIAYQgIAXgPAQQgQATgXALQgWALgdAAIgSAAQg0AAAAgtQAAgQAGgIQAGgJAKgEQAJgEAMgCQALgCAJgDQAKgDAHgGQAHgHAAgNQAAgegkAAIg9AAIAADzQAAA7g5AAQgdAAgOgPg");
	this.shape.setTransform(1.7,0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#015579").s().p("AuQFyQgeAAAAgbIAAqtQAAgbAeAAIchAAQAeAAAAAbIAAKtQAAAbgeAAg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-94.2,-36.9,188.6,74.1);
p.frameBounds = [rect];


(lib.btnNext_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.btnNext();
	this.instance.setTransform(-30.9,-28.4);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-30.9,-28.4,62,57);
p.frameBounds = [rect];


(lib.btnHome_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.btnHome();
	this.instance.setTransform(-30.9,-28.4);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-30.9,-28.4,62,57);
p.frameBounds = [rect];


(lib.btnGame_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.btnGame();
	this.instance.setTransform(-53.4,-25.9);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-53.4,-25.9,107,52);
p.frameBounds = [rect];


(lib.mainPage = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.btnGame = new lib.btnGame_1();
	this.btnGame.setTransform(-111.5,735.2);
	new cjs.ButtonHelper(this.btnGame, 0, 1, 1);

	this.btnNext = new lib.btnNext_1();
	this.btnNext.setTransform(91,716.7);
	new cjs.ButtonHelper(this.btnNext, 0, 1, 1);

	this.btnPrev = new lib.btnPrev_1();
	this.btnPrev.setTransform(-81,579.2);
	new cjs.ButtonHelper(this.btnPrev, 0, 1, 1);

	this.btnHome = new lib.btnHome_1();
	this.btnHome.setTransform(-89,647.2);
	new cjs.ButtonHelper(this.btnHome, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btnHome,p:{x:-89,y:647.2,scaleX:1,scaleY:1}},{t:this.btnPrev,p:{x:-81,y:579.2,scaleX:1,scaleY:1}},{t:this.btnNext,p:{x:91,y:716.7}},{t:this.btnGame,p:{x:-111.5,y:735.2,scaleX:1,scaleY:1}}]}).to({state:[{t:this.btnHome,p:{x:119,y:724.7,scaleX:1,scaleY:1}},{t:this.btnPrev,p:{x:47,y:724.7,scaleX:1,scaleY:1}},{t:this.btnNext,p:{x:191,y:724.7}},{t:this.btnGame,p:{x:-96.5,y:733.2,scaleX:1,scaleY:1}}]},1).to({state:[{t:this.btnHome,p:{x:119,y:724.7,scaleX:1,scaleY:1}},{t:this.btnPrev,p:{x:47,y:724.7,scaleX:1,scaleY:1}},{t:this.btnNext,p:{x:191,y:724.7}},{t:this.btnGame,p:{x:-78.5,y:723.2,scaleX:1,scaleY:1}}]},1).to({state:[{t:this.btnHome,p:{x:104.6,y:728.7,scaleX:0.86,scaleY:0.86}},{t:this.btnPrev,p:{x:42.6,y:728.7,scaleX:0.86,scaleY:0.86}},{t:this.btnNext,p:{x:-52,y:728.7}},{t:this.btnGame,p:{x:187.6,y:727.4,scaleX:0.86,scaleY:0.86}}]},1).wait(1));

	// Layer 1
	this.instance = new lib.page1();

	this.instance_1 = new lib.page2();

	this.instance_2 = new lib.page3();

	this.instance_3 = new lib.page4();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-165,0,1189.1,768);
p.frameBounds = [rect, new cjs.Rectangle(-150,0,1174.1,768), new cjs.Rectangle(-132,0,1156.1,768), new cjs.Rectangle(-83,0,1107.1,768)];


(lib.instructions = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#015579").s().p("AOSIuQggAAAAgiIAAgBQAAgiAhgBIBIAAQAIAAADgDQADgEABgFQgBgFgDgEQgDgEgIAAIgkAAQhJAAgBhMQAAhQBQAAIA3AAQAhAAABAiIAAABQgCAighABIg7AAQgHAAgEADQgDAEAAAFQAAAEADAFQAEADAHAAIAjAAQBLABAABMQAABQhOAAgAMeIpQgHgEgFgJIgnhHQgLgOAAgPQAAgLAEgFQADgFAHgDQAFgDAHgBIANgDQAFgBAFgEQAEgFAAgIQABgSgWAAIgmAAIAACWQAAAjgjAAQgRAAgJgJQgIgJAAgRIAAi1QAAgjAhAAIBKAAQAXAAAPAHQAQAGALALQALAKAFAOQAFAOAAAOQAAAVgLATQgLATgUAKIAdAvQAHALAAAMQAAAHgDAGQgDAHgFAGQgFAEgGAEQgGACgHAAQgIAAgHgFgAHgIuQgjAAAAgjIAAi1QAAgjAjAAIB1AAQAQAAAKAKQAIAKABAPQgBAOgIALQgKAJgQABIhTAAIAAAUIBCAAQARAAAJALQAJAKAAAPQAAAOgJAKQgJALgRAAIhCAAIAAAUIBTAAQAQAAAKAKQAIALABAOQgBAPgIAKQgKAKgQAAgAiIIuQgiAAAAgjIAAi1QAAgjAiAAIB2AAQAQAAAHAKQAKAKgBAPQABAOgKALQgHAJgQABIhTAAIAAAUIBCAAQAQAAAKALQAJAKAAAPQAAAOgJAKQgKALgQAAIhCAAIAAAUIBTAAQAQAAAHAKQAKALgBAOQABAPgKAKQgHAKgQAAgAkkIuQgjAAAAgjIAAi1QAAgRAKgJQAKgJAPAAQAOAAAKAJQAKAJAAARIAACSIAlAAQAPAAAJAKQAJALgBAOQABAPgJAKQgJAKgPAAgApPIuQgiAAAAgjIAAi1QAAgjAiAAIB2AAQAPAAAKAKQAJAKAAAPQAAAOgJALQgKAJgPABIhTAAIAAAUIBCAAQAQAAAKALQAIAKABAPQgBAOgIAKQgKALgQAAIhCAAIAAAUIBTAAQAPAAAKAKQAJALAAAOQAAAPgJAKQgKAKgPAAgAEyIlQgLgJAAgRIAAiSIgYAAQgQgBgJgJQgKgLAAgOQAAgPAKgKQAJgKAQAAIB1AAQAQAAAKAKQAJAKAAAPQAAAOgJALQgKAJgQABIgYAAIAACSQABARgLAJQgKAJgOAAQgOAAgKgJgABoIlQgKgJAAgRIAAiSIgYAAQgRgBgIgJQgKgLAAgOQAAgPAKgKQAIgKARAAIB1AAQAQAAAKAKQAJAKAAAPQAAAOgJALQgKAJgQABIgXAAIAACSQgBARgJAJQgLAJgOAAQgOAAgLgJgArKIlQgKgJAAgRIAAg3Ig4AAIAAA3QgBARgJAJQgLAJgOAAQgOAAgLgJQgKgJAAgRIAAi1QAAgRAKgJQALgJAOAAQAOAAALAJQAJAJABARIAAA3IA4AAIAAg3QAAgRAKgJQAKgJAPAAQANAAALAJQAKAJAAARIAAC1QAAARgKAJQgLAJgNAAQgPAAgKgJgAvdIlQgKgJAAgRIAAiSIgYAAQgRgBgJgJQgJgLAAgOQAAgPAJgKQAJgKARAAIB1AAQAQAAAKAKQAIAKABAPQgBAOgIALQgKAJgQABIgYAAIAACSQAAARgKAJQgKAJgPAAQgNAAgLgJgAOaB2QgXgKgRgRQgSgRgJgYQgLgXAAgaQAAgZALgYQAJgXASgRQARgSAXgKQAZgKAaAAQAaAAAYAKQAYAKARASQARARALAXQAKAYgBAZQABAagKAXQgLAYgRARQgRARgYAKQgYALgagBQgaABgZgLgAO2gyQgKAEgIAIQgIAIgEAKQgFALAAAKQAAAMAFALQAEALAIAIQAIAHAKAFQALAFAMgBQAMABALgFQALgFAHgHQAJgIAEgLQAFgLgBgMQABgKgFgLQgEgKgJgIQgHgIgLgEQgLgFgMAAQgMAAgLAFgAAgB6QgIgFgFgMIgJgbIhJAAIgKAbQgFAMgIAFQgIAFgKAAQgHAAgHgCQgGgDgGgEQgFgEgDgGQgDgGAAgIQAAgHACgGIBTi1QAGgMAJgFQAKgHAJABQAKgBAJAHQAHAFAFAMIBLC1QADAGAAAHQABAIgEAGQgDAGgGAEQgFAEgGADQgIACgGAAQgKAAgIgFgAgpAXIAiAAIgQgrgA0WB6QgIgFgFgMIgKgbIhKAAIgKAbQgFAMgIAFQgIAFgKAAQgHAAgGgCQgHgDgFgEQgGgEgDgGQgDgGAAgIQAAgHADgGIBTi1QAFgMAJgFQAKgHAJABQAKgBAJAHQAJAFAEAMIBNC1QADAGAAAHQgBAIgDAGQgDAGgFAEQgGAEgHADQgGACgHAAQgJAAgJgFgA1hAXIAhAAIgPgrgEAinAB/QgiAAAAgjIAAizQAAgjAiAAIB2AAQAPAAAKAKQAJAKAAAPQAAAOgJALQgKAJgPABIhTAAIAAAUIBCAAQAQAAAKALQAIAKABAMQgBAPgIAKQgKALgQAAIhCAAIAAAUIBTAAQAPABAKAJQAJALAAAOQAAAPgJAKQgKAKgPAAgAcHB/QgjAAABgjIAAizQgBgjAjAAIB2AAQAPAAAKAKQAJAKAAAPQAAAOgJALQgKAJgPABIhUAAIAAAUIBDAAQAQAAAKALQAIAKABAMQgBAPgIAKQgKALgQAAIhDAAIAAAUIBUAAQAPABAKAJQAJALAAAOQAAAPgJAKQgKAKgPAAgAZqB/QgjAAAAgjIAAizQABgRAJgJQALgJAOAAQAOAAAKAJQALAJAAARIAACQIAkAAQAQABAJAJQAIALAAAOQAAAPgIAKQgJAKgQAAgAV+B2QgJgJAAgRIAAizQAAgjAiAAIBGAAQAXAAAQAHQAQAGAMAMQAKALAGAPQAEAOAAAPQAAAQgEAOQgFAMgKALQgJAMgOAGQgNAIgRAAIgMAAQgfAAgBgcQABgJADgFQAEgGAGgCQAGgDAGgBIANgDQAGgBAEgEQAEgFABgIQAAgSgWAAIglAAIAACTQgBAkgiAAQgSAAgIgJgAL4B/QgfAAgXgKQgYgMgQgQQgPgSgIgWQgIgXAAgXQAAgWAIgXQAIgWARgSQAPgSAZgMQAZgKAhAAIAUAAQAIAAAHACQAGAEAFAEQAEAGACAGQACAGABAHQgBAHgCAGQgCAGgEAGQgFAEgGAEQgHADgIAAIgaAAQgPAAgLAEQgKAEgIAJQgGAHgEAKQgEAKAAAIQAAALAEAKQAEAKAGAIQAIAHAKAGQAMAEAOAAIAaAAQAIABAHACQAGADAFAFQAEAFACAHQACAGAAAGQAAAOgJALQgIAKgRAAgAFyB/QgRAAgKgJQgJgKAAgQIAAizQAAgHADgHQACgFAGgGQAFgEAGgEQAHgCAHAAIAhAAQAhAAAZAKQAYAMAPASQARASAIAWQAJAXAAAWQAAAXgIAXQgJAWgPASQgQAQgXAMQgYAKgfAAgAGSA5IAHAAQAOABAKgGQAKgFAIgIQAHgIAEgKQADgKAAgLQAAgIgDgKQgEgKgHgHQgGgHgLgFQgLgEgPAAIgGAAgAmGB/QghAAAAgiIAAgBQABgjAgAAIBJAAQAHAAADgDQAEgFAAgEQAAgFgEgEQgDgEgHAAIgkAAQhKAAAAhKQAAhQBPAAIA4AAQAhAAAAAiIAAABQgBAighABIg8AAQgGAAgEADQgEAFABAEQgBAEAEAFQAEAEAGAAIAkAAQBKAAAABKQAABQhOAAgAsmB/QgiAAgBgjIAAizQABgjAiAAIB2AAQAQAAAJAKQAJAKAAAPQAAAOgJALQgJAJgQABIhTAAIAAAUIBBAAQARAAAKALQAJAKAAAMQAAAPgJAKQgKALgRAAIhBAAIAAAUIBTAAQAQABAJAJQAJALAAAOQAAAPgJAKQgJAKgQAAgAvDB/QgjAAABgjIAAizQAAgRAKgJQAKgJAOAAQAOAAAKAJQAKAJAAARIAACQIAlAAQAQABAIAJQAJALAAAOQAAAPgJAKQgIAKgQAAgAynB/QghAAAAgjIAAizQAAgjAfAAIBvAAQAOAAALAGQALAFAHAKQAHAKAEAMQAEAMAAANQAAALgDAKQgDAKgFAIQgGAIgHAFQgJADgKAAQAVAEAKARQAKARAAAUQAAANgEAMQgDAMgHAKQgGAJgLAGQgKAGgOAAgAyGA5IA0AAQAHAAAEgDQADgFAAgEQAAgFgDgEQgEgEgHAAIg0AAgAyGgXIA0AAQAGAAAFgFQADgFAAgGQAAgFgDgFQgEgDgHAAIg0AAgA9rB/QgiAAAAgjIAAizQAAgjAiAAIB2AAQAQAAAJAKQAJAKAAAPQAAAOgJALQgJAJgQABIhTAAIAAAUIBCAAQAQAAAKALQAJAKAAAMQAAAPgJAKQgKALgQAAIhCAAIAAAUIBTAAQAQABAJAJQAJALAAAOQAAAPgJAKQgJAKgQAAgAf5B2QgKgJAAgRIAAiQIgYAAQgRgBgJgJQgJgLAAgOQAAgPAJgKQAJgKARAAIB1AAQAQAAAJAKQAJAKAAAPQAAAOgJALQgJAJgQABIgYAAIAACQQAAARgKAJQgKAJgPAAQgNAAgLgJgAUcB2QgKgJAAgRIAAhoIgfAoQgKAMgLAAQgMAAgIgNIgfgnIAABoQAAARgKAJQgKAJgOAAQgOAAgKgJQgLgJABgRIAAiwQgBgUAIgJQAGgJATAAQASAAAIAGQAKAFAHAJIAuA7IAtg7QAHgJAJgFQAKgGAOAAQATAAAIAJQAHAJAAAUIAACwQAAARgKAJQgKAJgOAAQgOAAgLgJgAEBB9QgFgCgEgDIgFgEIgEgFIg9haIAABHQAAARgKAJQgKAJgOAAQgOAAgKgJQgLgJABgRIAAizQgBgRALgJQAKgJAOAAIACAAQASAAAIAQIA/BfIAAhMQAAgRAKgJQALgJAOAAQAOAAAKAJQAKAJAAARIAACzQAAARgKAJQgKAJgOAAQgIgBgFgBgAo0B2QgKgJAAgRIAAiQIgYAAQgRgBgJgJQgKgLAAgOQAAgPAKgKQAJgKARAAIB1AAQAQAAAKAKQAIAKABAPQgBAOgIALQgKAJgQABIgYAAIAACQQAAARgKAJQgLAJgOAAQgOAAgKgJgA4lB2QgKgJAAgRIAAiQIgYAAQgRgBgJgJQgJgLAAgOQAAgPAJgKQAJgKARAAIB1AAQAQAAAKAKQAIAKABAPQgBAOgIALQgKAJgQABIgYAAIAACQQAAARgKAJQgLAJgOAAQgOAAgKgJgA/lB2QgKgJAAgRIAAg3Ig5AAIAAA3QAAARgKAJQgKAJgOAAQgOAAgLgJQgKgJAAgRIAAizQAAgRAKgJQALgJAOAAQAOAAAKAJQAKAJAAARIAAA3IA5AAIAAg3QAAgRAKgJQAKgJAOAAQAOAAAKAJQAKAJAAARIAACzQAAARgKAJQgKAJgOAAQgOAAgKgJgEgj5AB2QgKgJAAgRIAAiQIgYAAQgRgBgIgJQgKgLAAgOQAAgPAKgKQAIgKARAAIB1AAQAQAAAKAKQAJAKAAAPQAAAOgJALQgKAJgQABIgXAAIAACQQgBARgJAJQgLAJgOAAQgOAAgLgJgAPlk3QgYgKgQgRQgSgRgKgXQgKgYAAgbQAAgaAKgYQAKgXASgRQAQgSAYgKQAYgKAaAAQAaAAAZAKQAXAKARASQARARALAXQAKAYAAAaQAAAbgKAYQgLAXgRARQgRARgXAKQgZALgagBQgaABgYgLgAQBnhQgLAEgIAIQgHAIgFALQgFAKABAMQgBAMAFALQAFAKAHAJQAIAHALAFQALAFALAAQANAAALgFQAKgFAIgHQAIgJAEgKQAFgLAAgMQAAgMgFgKQgEgLgIgIQgIgIgKgEQgLgFgNAAQgLAAgLAFgAkyk3QgXgKgRgRQgRgRgKgXQgLgYABgbQgBgaALgYQAKgXARgRQARgSAXgKQAYgKAaAAQAbAAAYAKQAXAKASASQARARAKAXQAKAYAAAaQAAAbgKAYQgKAXgRARQgSARgXAKQgYALgbgBQgaABgYgLgAkVnhQgLAEgIAIQgIAIgFALQgEAKAAAMQAAAMAEALQAFAKAIAJQAIAHALAFQAKAFAMAAQAMAAALgFQALgFAIgHQAHgJAFgKQAFgLAAgMQAAgMgFgKQgFgLgHgIQgIgIgLgEQgLgFgMAAQgMAAgKAFgAZ8kzQgJgFgEgMIgJgbIhLAAIgKAbQgFAMgIAFQgIAFgKAAQgHABgHgDQgGgDgFgEQgGgEgDgGQgDgGAAgIQAAgHADgGIBSi3QAGgMAJgFQAKgHAJAAQAKAAAJAHQAJAFAEAMIBNC3QACAGAAAHQABAIgEAGQgDAGgFAEQgGAEgGADQgIADgGgBQgKAAgIgFgAYxmVIAhAAIgPgtgA6XkzQgJgFgEgMIgKgbIhKAAIgKAbQgFAMgIAFQgJAFgJAAQgHABgHgDQgGgDgFgEQgGgEgDgGQgDgGAAgIQAAgHADgGIBSi3QAGgMAJgFQAKgHAJAAQAKAAAJAHQAJAFAEAMIBNC3QACAGAAAHQAAAIgDAGQgDAGgFAEQgGAEgHADQgGADgHgBQgJAAgJgFgA7imVIAhAAIgPgtgAfmkuQgeAAgYgKQgYgMgPgQQgQgSgIgWQgIgWAAgYQABgYAHgXQAIgWARgSQAQgSAZgMQAYgKAhAAIAUAAQAIAAAHACQAGAEAFAEQAFAGACAGQACAHAAAGQAAAHgCAGQgCAGgFAGQgFAEgGAEQgHACgIAAIgaAAQgOABgLAEQgKAEgIAJQgHAHgEAKQgDAKAAAKQAAALADAKQAEAKAHAIQAIAHAKAGQALAEAOAAIAaAAQAIAAAHADQAGADAFAFQAFAFACAHQABAGAAAGQABAOgJALQgJAKgRAAgAV8kuQggAAgXgKQgYgMgQgQQgPgSgIgWQgIgWABgYQAAgYAIgXQAIgWAQgSQAQgSAZgMQAYgKAhAAIAUAAQAJAAAGACQAGAEAFAEQAEAGACAGQADAHAAAGQAAAHgDAGQgCAGgEAGQgFAEgGAEQgGACgJAAIgZAAQgPABgLAEQgLAEgHAJQgHAHgEAKQgDAKgBAKQABALADAKQAEAKAHAIQAHAHALAGQALAEAOAAIAaAAQAJAAAGADQAGADAFAFQAEAFACAHQACAGAAAGQABAOgKALQgIAKgRAAgAHakuQgiAAAAgjIAAi2QAAgiAiAAIB2AAQAQAAAJAKQAKALgBANQABAPgKALQgJAKgQAAIhTAAIAAAUIBCAAQAQAAAKALQAJAKAAAOQAAAPgJAKQgKAKgQAAIhCAAIAAAVIBTAAQAQABAJAJQAKALgBAOQABAOgKALQgJAKgQAAgAE+kuQgjAAAAgjIAAi2QAAgQAKgJQAKgJAPAAQAOAAAKAJQAKAJAAAQIAACTIAlAAQAPABAJAJQAJALgBAOQABAOgJALQgJAKgPAAgAo8kuQgiAAAAgjIAAi2QAAgiAgAAIBvAAQAOAAALAGQALAFAHAKQAHAKAEAMQADAMAAANQAAALgDAKQgDAKgFAIQgFAIgIAFQgJAFgKAAQAWAEAJARQALARgBAVQAAAMgDAMQgEAMgGAKQgHAJgKAGQgLAGgNAAgAocl0IA0AAQAIAAADgDQADgEABgFQgBgFgDgEQgDgEgIAAIg0AAgAocnGIA0AAQAHAAAEgFQADgFABgGQgBgFgDgFQgDgDgIAAIg0AAgAtmkuQgiAAAAgjIAAi2QAAgiAiAAIB2AAQAPAAAKAKQAJALAAANQAAAPgJALQgKAKgPAAIhTAAIAAAUIBCAAQAQAAAKALQAIAKABAOQgBAPgIAKQgKAKgQAAIhCAAIAAAVIBTAAQAPABAKAJQAJALAAAOQAAAOgJALQgKAKgPAAgA3ekuQgfAAgYgKQgXgMgQgQQgQgSgIgWQgHgWAAgYQAAgYAIgXQAIgWAQgSQAQgSAZgMQAZgKAgAAIAUAAQAJAAAGACQAHAEAEAEQAFAGACAGQADAHgBAGQABAHgDAGQgCAGgFAGQgEAEgHAEQgGACgJAAIgZAAQgPABgKAEQgLAEgHAJQgHAHgFAKQgDAKAAAKQAAAKADAJQADAKAGAHQAHAIAJAGQAJAFAMABIAAgpQAAgRALgIQAJgKAPABQAOgBAKAKQAKAIAAARIAABMQABAQgLAKQgKAJgPAAgA+QkyQgHgFgGgKIgnhGQgLgOAAgPQAAgLAEgFQAEgGAGgCQAGgDAGgBIANgDQAGgCAEgDQAFgEAAgIQAAgTgWAAIglAAIAACVQgBAkgiAAQgSAAgIgJQgJgJAAgRIAAi2QAAgiAiAAIBKAAQAWAAAQAHQAQAGALALQAKAKAFAOQAGANgBAPQAAAVgLATQgKATgVAKIAeAvQAGALABALQAAAIgEAHQgDAHgEAFQgFAFgHADQgFACgHAAQgIAAgHgEgEgjWgEuQgRAAgKgKQgJgJAAgQIAAi2QAAgGADgGQADgGAFgGQAGgEAGgEQAHgCAGAAIAiAAQAgAAAZAKQAYAMAQASQARASAHAWQAJAXAAAYQAAAYgIAWQgIAWgPASQgQAQgYAMQgXAKgfAAgEgi1gF0IAGAAQAOABAKgGQALgFAHgIQAHgIAEgKQAEgKAAgLQAAgLgEgJQgDgJgIgIQgGgIgLgEQgLgEgOgBIgGAAgEAjHgE3QgKgJAAgRIAAg4Ig4AAIAAA4QAAARgKAJQgLAIgOAAQgOAAgLgIQgJgJgBgRIAAi2QABgQAJgJQALgJAOAAQAOAAALAJQAKAJAAAQIAAA4IA4AAIAAg4QAAgQAKgJQALgJANAAQAOAAALAJQAKAJAAAQIAAC2QAAARgKAJQgLAIgOAAQgNAAgLgIgAbkk3QgLgJAAgRIAAiSIgYAAQgQAAgJgKQgKgLAAgPQAAgNAKgLQAJgKAQAAIB1AAQAQAAAKAKQAJALAAANQAAAPgJALQgKAKgQAAIgYAAIAACSQABARgLAJQgKAIgOAAQgOAAgKgIgAMgk3QgKgJAAgRIAAiSIgYAAQgRAAgJgKQgJgLAAgPQAAgNAJgLQAJgKARAAIB1AAQAQAAAKAKQAIALABANQgBAPgIALQgKAKgQAAIgYAAIAACSQAAARgKAJQgKAIgPAAQgNAAgLgIgACQk3QgLgJAAgRIAAiSIgYAAQgQAAgJgKQgKgLAAgPQAAgNAKgLQAJgKAQAAIB1AAQAQAAAKAKQAJALAAANQAAAPgJALQgKAKgQAAIgYAAIAACSQABARgLAJQgKAIgOAAQgOAAgKgIgAg4k3QgKgJAAgRIAAiSIgYAAQgRAAgIgKQgKgLAAgPQAAgNAKgLQAIgKARAAIBzAAQAQAAAKAKQAJALAAANQAAAPgJALQgKAKgQAAIgXAAIAACSQgBARgHAJQgLAIgOAAQgOAAgLgIgAvhk3QgKgJAAgRIAAg4Ig4AAIAAA4QgBARgJAJQgLAIgOAAQgOAAgLgIQgKgJAAgRIAAi2QAAgQAKgJQALgJAOAAQAOAAALAJQAJAJABAQIAAA4IA4AAIAAg4QAAgQAKgJQAKgJAPAAQANAAALAJQAKAJAAAQIAAC2QAAARgKAJQgLAIgNAAQgPAAgKgIgAz0k3QgKgJAAgRIAAiSIgYAAQgRAAgJgKQgJgLAAgPQAAgNAJgLQAJgKARAAIB1AAQAQAAAKAKQAIALABANQgBAPgIALQgKAKgQAAIgYAAIAACSQAAARgKAJQgKAIgPAAQgNAAgLgIg");
	this.shape.setTransform(-5.3,-42.9);

	this.btnPlay = new lib.btnPlay();
	this.btnPlay.setTransform(-0.9,75.1);
	new cjs.ButtonHelper(this.btnPlay, 0, 1, 1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#84C04F").s().p("Egt4ASmQhgAAAAhXMAAAgidQAAhXBgAAMBbxAAAQBfAAAABXMAAAAidQAABXhfAAg");
	this.shape_1.setTransform(-1.6,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#015579").s().p("EgvzAUeQhkAAAAhkMAAAglzQAAhkBkAAMBfnAAAQBkAAAABkMAAAAlzQAABkhkAAgEgvVgROMAAAAidQAABXBgAAMBbwAAAQBgAAAAhXMAAAgidQAAhWhgAAMhbwAAAQhgAAAABWg");
	this.shape_2.setTransform(-1.9,0);

	this.addChild(this.shape_2,this.shape_1,this.btnPlay,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-318,-130.9,632.2,262.1);
p.frameBounds = [rect];


(lib.gameOver = function() {
	this.initialize();

	// Layer 1
	this.btnHome = new lib.btnHome_1();
	this.btnHome.setTransform(3,38.1);
	new cjs.ButtonHelper(this.btnHome, 0, 1, 1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1F4C2D").s().p("AXWDCQgngRgcgcQgcgcgRgnQgRgmAAgsQAAgpARgnQARgnAcgcQAcgdAngRQAngQArAAQArAAAoAQQAmARAcAdQAdAcARAnQAQAnABApQgBAsgQAmQgRAngdAcQgcAcgmARQgoAQgrAAQgrAAgngQgAYDhVQgRAIgNANQgNAMgHASQgHARgBATQABATAHASQAHARANANQANANARAHQASAIAUAAQATAAATgIQARgHANgNQAMgNAIgRQAIgSAAgTQAAgTgIgRQgIgSgMgMQgNgNgRgIQgTgHgTAAQgUAAgSAHgEgiAADCQgmgRgcgcQgdgcgQgnQgRgmAAgsQAAgpARgnQAQgnAdgcQAcgdAmgRQAngQAsAAQArAAAnAQQAnARAcAdQAdAcAQAnQARAnAAApQAAAsgRAmQgQAngdAcQgcAcgnARQgnAQgrAAQgsAAgngQgEghSgBVQgRAIgOANQgNAMgGASQgIARAAATQAAATAIASQAGARANANQAOANARAHQARAIAVAAQATAAASgIQASgHAMgNQANgNAHgRQAIgSAAgTQAAgTgIgRQgHgSgNgMQgMgNgSgIQgSgHgTAAQgVAAgRAHgAMtDIQgOgJgIgTIgPgsIh6AAIgSAsQgHATgOAJQgNAIgQAAQgMAAgKgDQgLgEgJgHQgJgIgGgJQgEgKAAgMQAAgNAEgKICIkqQAJgUAPgJQAPgKAQAAQARAAAPAKQAOAJAHAUIB9EqQAGAKAAANQAAALgGAKQgFAKgJAIQgJAHgLAEQgLADgLAAQgQAAgNgIgAKxAmIA3AAIgZhIgAnvDIQgOgJgGgTIgRgsIh5AAIgRAsQgJATgNAJQgNAIgQAAQgMAAgKgDQgLgEgJgHQgKgIgEgJQgGgKAAgMQAAgNAGgKICIkqQAIgUAQgJQAPgKAPAAQAQAAAPAKQAPAJAIAUIB9EqQAEAKAAANQAAALgEAKQgGAKgJAIQgJAHgLAEQgLADgLAAQgQAAgOgIgAppAmIA3AAIgahIgEAn4AC/QgRgRAAgYQAAgXARgRQARgRAXAAQAYAAARARQAQARAAAXQAAAYgQARQgRARgYAAQgXAAgRgRgEAjNADQQg3AAAAg4IAAgCQABg5A2AAIB3AAQAMAAAFgGQAGgHgBgHQABgIgGgHQgFgGgMAAIg7AAQh5AAAAh7QgBiECCAAIBbAAQA3AAAAA3IAAACQgCA6g2AAIhiAAQgLAAgFAGQgGAHAAAHQAAAIAGAHQAFAGALAAIA8AAQB4AAAAB7QAACEiAAAgAFQDQQg5AAAAg6IAAkoQAAgbARgPQARgOAXAAQAWAAARAOQARAPABAbIAADvIA8AAQAaAAAOARQAOARAAAXQAAAYgOARQgOARgaAAgAhiAaIAAisQAAgbARgPQARgOAXAAQAYAAAQAOQAPAPAAAbIAAC9QAAA0A2AAQA1AAAAg0IAAi9QgBgbASgPQAQgOAXAAQAYAAARAOQAQAPAAAbIAACsQAAC2ilAAQinAAAAi2gAuIDJQgMgIgJgQIhAhzQgSgXAAgaQABgPAGgJQAGgIAKgFQAJgEALgCQALgCAKgDQAKgDAGgGQAIgGAAgNQAAgfgkAAIg9AAIAADzQAAA7g5AAQgdAAgPgPQgNgPAAgcIAAkoQAAg5A3AAIB6AAQAkAAAbALQAaALARARQASASAIAWQAJAWAAAYQAAAjgSAfQgRAdgkAQIAyBOQALASAAATQgBAMgEALQgFALgIAJQgHAIgLAEQgKAFgMAAQgMAAgMgHgAz+DQQgzAAgngSQgngRgZgdQgagcgMglQgOgkAAgnQAAglAOgmQANglAbgdQAbgeAogSQAogSA2AAIAhAAQAOAAALAFQAKAFAIAIQAGAIAFALQADAKAAALQAAALgDAKQgEALgHAIQgIAIgKAFQgLAFgOAAIgqAAQgYAAgRAIQgTAHgLANQgMANgHAQQgFAQAAAPQAAAQAFAQQAGAPAJANQALAMAPAJQAOAJAVACIAAhEQAAgZAQgPQARgOAYAAQAXAAAQAOQASAPgBAZIAAB9QAAAbgQAQQgQAPgZAAgEgmKADQQgzAAgngSQgngRgZgdQgagcgNglQgNgkAAgnQAAglANgmQAOglAbgdQAageAogSQApgSA2AAIAgAAQAPAAAKAFQALAFAHAIQAIAIADALQAEAKAAALQAAALgEAKQgDALgIAIQgHAIgLAFQgKAFgPAAIgpAAQgYAAgSAIQgSAHgLANQgMANgHAQQgFAQgBAPQABASAFAQQAHARAMANQALAMASAIQARAIAYAAIAqAAQAPAAAKAFQALAFAHAIQAIAIADALQADAKAAAKQAAAXgPARQgOASgcAAgEAgWADMQgIgCgGgFQgGgEgDgEIgGgHIhkiVIAAB1QAAAcgRAPQgRAOgXAAQgXAAgRgOQgRgPAAgcIAAkoQAAgbARgPQARgOAXAAIACAAQAeAAAOAZIBnCdIAAh+QAAgbARgPQARgOAXAAQAYAAAQAOQARAPAAAbIAAEoQAAAcgRAPQgQAOgYAAQgMAAgIgDgATMDBQgRgPAAgcIAAkoQAAgbARgPQARgOAXAAQAXAAARAOQARAPAAAbIAAEoQAAAcgRAPQgRAOgXAAQgXAAgRgOgAPXDBQgRgPAAgcIAAjuIgoAAQgbAAgPgRQgPgRAAgYQAAgXAPgRQAPgRAbAAIDBAAQAbAAAPARQAPARAAAXQAAAYgPARQgPARgbAAIgnAAIAADuQAAAcgRAPQgRAOgXAAQgXAAgRgOgAlEDBQgRgPAAgcIAAjuIgoAAQgbAAgPgRQgPgRAAgYQAAgXAPgRQAPgRAbAAIDBAAQAbAAAPARQAPARAAAXQAAAYgPARQgPARgbAAIgnAAIAADuQAAAcgRAPQgRAOgXAAQgXAAgRgOgA5ADMQgIgCgFgFQgGgEgEgEIgGgHIhkiVIAAB1QAAAcgRAPQgQAOgYAAQgWAAgSgOQgRgPAAgcIAAkoQAAgbARgPQASgOAWAAIADAAQAeAAAOAZIBnCdIAAh+QAAgbAQgPQARgOAYAAQAXAAARAOQAQAPABAbIAAEoQgBAcgQAPQgRAOgXAAQgMAAgJgDgEAn3ABNQgRgPABgbIAAi1QgBgbARgPQARgOAXAAQAYAAAQAOQAQAPABAbIAAC1QgBAbgQAPQgQAPgYAAQgXAAgRgPg");
	this.shape.setTransform(-1.3,-27.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#84C04F").s().p("Egt4AMWQhfAAAAhXIAA19QAAhXBfAAMBbwAAAQBhAAAABXIAAV9QAABXhhAAg");
	this.shape_1.setTransform(0.3,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#015579").s().p("EgvzAOOQhkAAAAhkIAA5TQAAhkBkAAMBfnAAAQBkAAAABkIAAZTQAABkhkAAg");

	this.addChild(this.shape_2,this.shape_1,this.shape,this.btnHome);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(-316,-90.9,632.2,182.1);
p.frameBounds = [rect];


(lib.pgeSet = function() {
	this.initialize();

	// Layer 1
	this.main = new lib.mainPage();
	this.main.setTransform(384,429.4,1,1,90,0,0,429.4,384);

	this.addChild(this.main);
}).prototype = p = new cjs.Container();
p.nominalBounds = rect = new cjs.Rectangle(0,-165,768,1189.1);
p.frameBounds = [rect];

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;